eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:1337/eureka/
    # improve refresh time
    registryFetchIntervalSeconds: 5
  # improve refresh time
  instance.leaseRenewalIntervalInSeconds: 5
  server.response-cache-update-interval-ms: 1000
link:
    expiration: 3600  
jwt:
    expiration: 604800
    header: Authorization
    issuer: holter.io
    prefix: Bearer
    route:
      authentication:
        create: /sandeep
        refresh: /refresh
    secret: my^hol67TR
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?autoReconnect=true&serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: 
  main:
    allow-bean-definition-overriding: true

holter:
  apigateway:
    url: 65.1.169.141:8090
  username: admin
  password: sandeep   
cardio:
  config:
    aws:
      region: ap-south-1
#       accessKey: ENC(5LPEc5Qt/h/WhX9g01UgvRyPmd+MxQzT2MletVYQ02U=)
#       secretKey: ENC(n4pwMuEvx97LgwfHl6FyKKGj4H9YVgtJvmHw8qXFrvJyv/19GKHMDij/CJqPBYr2wsUwlKYhI48=)
    ses:
      region: ap-south-1
#       accessKey: ENC(crdoHqXGiU43p+esD/L0VRs1QvKBSCA5oK1myOiXkzc=)
#       secretKey: ENC(ZXq8wgUlcgQqH2Dl8BH0ydqqFOrujL9eJezMH41zKaLaIKoJGck4zMdsySb07BrR7YbR6OxTxlo=)
      port: 587
      host: email-smtp.ap-south-1.amazonaws.com
      fromEmail: support@kavanant.com
    bucket: cardio-new-dev-assets
jasypt:
 encryptor:
  password: Cardio-Secret-!290Dev
  
 

management:
  endpoints:
    web:
      exposure:
        include: "*"
